### ISSUE TITLE
[Enhancement] add `faction=Custom` and `faction_lock=yes` to monster sides.

### ISSUE THREAD

**Issue by knyghtmare** [Jonathan-Kelly/Improved_The_Wilderlands#2]
Some mods can modify the flag variant of the sides and this reveals the spoiler that the brown sides are not just one side.

**Comment by Jonathan-Kelly** [comment]
That the wildlife attack each other is not really meant to be a secret. Their sides are only hidden to keep the Status Table from being overpopulated with dozens of sides which do not even use the economy mechanics it displays.

**Comment by knyghtmare** [comment]
Ah, it's okay then.
